# Generated by Django 4.2.16 on 2024-10-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinguisticData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_id', models.CharField(max_length=10)),
                ('word_count', models.IntegerField()),
                ('char_count', models.IntegerField()),
                ('avg_word_length', models.FloatField()),
                ('language', models.CharField(max_length=50)),
            ],
        ),
    ]
