# Generated by Django 4.2.16 on 2024-10-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linguistic_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linguisticdata',
            name='original_text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
